import { appWithTranslation } from 'next-i18next';
import { Provider } from "react-redux";
import { createWrapper } from "next-redux-wrapper";
import store from "../redux/store";
import Layout from '../components/Layout/Layout';
import Head from 'next/head'
import React,{useEffect} from 'react';
import '../styles/css/bootstrap.min.css'
import '../styles/css/nice-select.css'
import '../styles/css/font-awesome.min.css'
import '../styles/css/icofont.css'
import '../styles/css/slicknav.min.css'
import '../styles/css/owl-carousel.css'
import "../styles/css/datepicker.css"
// import '../styles/css/font-awesome.min.css'
import '../styles/css/animate.min.css'
import '../styles/css/magnific-popup.css'
// import '../styles/css/bootstrap.min.css'
import "../styles/css/normalize.css"
import '../styles/css/style.css'
import '../styles/css/responsive.css'
import '../styles/css/color/color1.css'

import '../styles/globals.css'

import AOS from 'aos';
import 'aos/dist/aos.css';

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    AOS.init();
  }, [])
  return <>
    <Head>
      <title>yangi zamon</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="stylesheet" id="colors" />
      <link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;display=swap" rel="stylesheet"></link>
    </Head>
    <Layout>
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </Layout>
  </>
}
const makeStore = () => store;
const wrapper = createWrapper(makeStore);
export default wrapper.withRedux(appWithTranslation(MyApp))
