import '../styles/globals.css'
import { appWithTranslation } from 'next-i18next';
import Headers from '../components/Header/header'
import { Provider } from "react-redux";
import { createWrapper } from "next-redux-wrapper";
import store from "../redux/store";
import Layout from '../components/Layout/Layout';
import Head from 'next/head'
function MyApp({ Component, pageProps }) {
  return <>
   <Head>
        <title>yangi zamon</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
  </Head>
  <Layout>
    <Provider store={store}>
  <Headers/>
  <Component {...pageProps} />
  </Provider>
  </Layout>
  </>
}
const makeStore = () => store;
const wrapper = createWrapper(makeStore);
export default wrapper.withRedux(appWithTranslation(MyApp))
